version: "3.7"

services:
  shop-ol:
    container_name: my-shop-ol
    build:
      context: .
      dockerfile: Dockerfile.ol
    image: my-cool-service:ol
    environment:
      - SHOULD_FAIL=true
      - APPLICATION_SERVER=OpenLiberty
    ports:
      - 9080:9080
  shop-pm:
    container_name: my-shop-pm
    build:
      context: .
      dockerfile: Dockerfile.pm
    image: my-cool-service:pm
    environment:
      - SHOULD_FAIL=true
      - APPLICATION_SERVER=Payara Micro
    ports:
      - 9081:8080
  shop-tt:
    container_name: my-shop-tt
    build:
      context: .
      dockerfile: Dockerfile.tt
    image: my-cool-service:tt
    environment:
      - SHOULD_FAIL=true
      - APPLICATION_SERVER=Thorntail
    ports:
      - 9082:8080
  prometheus:
    image: quay.io/prometheus/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    depends_on:
      - shop-ol
      - shop-pm
      - shop-tt