global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: "store"
    scrape_interval: "15s"
    static_configs:
    - targets: ['shop:9080']